global:
  scrape_interval: 5s
  external_labels:
    site: prod

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_timeout: 4s
    params:
      module: 
        - http_2xx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - replacement: blackbox-exporter:9115
        target_label: __address__
    static_configs:
      - targets:
          - http://nginx:80

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"